name: CICD

on: 
  push:
    branches:
    -  main

jobs:
  stage:
    runs-on: ubuntu-latest

    steps:
    -  name: actions/checkout@v3
       run: |  
         ls -lrt 
         pwd
         cd deployement
         ls -lrt
         cat file2.txt
