name: CICD

on: 
  push:
    branches:
    -  main

jobs:
  stage:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3


    - name: verify
      run: |
         ls -lrt 
         pwd
         cat file1.txt
